-- require("core.options")
-- require("core.keymaps")
-- require("core.plugins")
-- require("core.colorscheme")
-- require("core.plugin_config")
require("core.lazy_core.lazy_setup")
require('avante_lib').load()
require('core.plugin_config.telescope')
require('core.plugin_config.lsp_config')
require('core.plugin_config.harpoon')
require('core.colorscheme')
require('core.keymaps')
require('core.options')
