-- require("core.options")
-- require("core.keymaps")
-- require("core.plugins")
-- require("core.colorscheme")
-- require("core.plugin_config")
require("core.lazy_core.lazy_setup")
require('avante_lib').load()
-- require("core.lazy_core.avante")
